resources/public/md/useful_libraries.md

Since Brenton Ashworth's original GitHub project for sandbar is no longer available, I have removed the link on the Useful Libraries page. There are still a couple of forks out there, but from what I can tell, there is not a canonical fork. Also the wiki that contained the most useful documentation is no longer available.

Remove Sandbar from Useful Libraries

---

resources/md/guestbook.md

The tutorial refers to "Buddy" instead of "Bouncer" in the section that talks about using a vector for passing multiple rules to a validator.

Correct "Buddy" to "Bouncer" in Guestbook tutorial

---

resources/docs-1.x/clojurescript.md
resources/md/clojurescript.md

Minor change in function. I think that this doesn't render correctly in clojurescript with the missing semicolon.

Label is a html element.

---

resources/md/sessions_cookies.md

Now that Luminus selectively enforces anti-forgery, it should be disabled by default. The examples in this section do not correctly include this line in each section?

add missing code to disable anti-forgery

---

resources/md/routes.md

Code won't run as it was missing a closing parens.

fix unbalanced parens

---

resources/md/routes.md

Parameters in request map are provided as keywords rather than
strings.

params are provided in request map as keywords

---

resources/md/repl.md

Moving http server stuff to separate adapter entails some change in
"Starting the Application from the REPL" section of documentation.

Documentation change according to latest luminus-template

---

resources/md/deployment.md

Hi,
I've written a Clojure app deployment guide for Linode docs, and I think it would be useful for Luminus users to have it mentioned here.

Add mention of deployment guide in Linode docs

---

resources/md/environment.md

Minor fix in environment docs.

Fix env example of nesting and hyphenation

---

resources/docs-1.x/html_templating.md

Since Hiccup is no longer bundled as a dependency, there is no longer a need to explain it in the docs.
Any feedback welcome!

Remove hiccup from templating docs

---

resources/docs-1.x/security.md

After lein new, I saw the csrf-token is already included in layout.clj, the current docs are outdated.

CSRF token is included by default

---

resources/md/guestbook.md

Having both 'since' and 'and' seems redundant. I suggest either to remove 'since' and replace 'and' with 'so' (as proposed), or leave 'since' and remove 'and'.

some minor grammar correction done in one of 2 possible ways

---

resources/md/database.md

On the "Database Access" page, there is an conman SQL function call which passes query arguments first, a connection second. In the current conman version, the arguments have to be switched around.

Fix argument order in SQL function call with conn

---

resources/docs-1.x/deployment.md

Added instructions to parse JNDI configuration. I put this under deployment / Tomcat because the issue will probably arise during a deploy to Tomcat and will probably not arise in other conditions, but this instructions could also be moved into the DB sections.

Added instructions to parse JNDI configurations

---

resources/md/database.md

Rather than reinventing the wheel and writing own functions, a great
library camel-snake-kebab, can be used to convert the keys of the
results from HugSQL query from snake_case to kebab-case.
Created this from this discussion: https://github.com/luminus-framework/luminus/issues/152

Use camel-snake-kebab for result key conversion

---

resources/public/css/screen.css

This ensures the :hover borders and the .selected borders are aligned, and also prevents the underline from extending beyond the width of the nav text.

Align borders in main nav

---

resources/md/database.md

Not just :1 and :*. This makes it consistent no matter what syntax you use in your sql file. Not having this produced very unexpected results.

Trigger case massaging on :one and :many.

---

resources/md/deployment.md

@yogthos We spoke on slack the other day about migrations at start up for when heroku is low on resources. Please see my addition to the docs.

added heroku automatic migration instructions

---

resources/md/repl.md

Add section with "correct" instructions for running the Application in the Boot REPL. I had to follow these instructions to make it work, at any rate.

Update REPL instructions for Boot users.

---

resources/md/profiles.md

Remove +cider, and add +boot. Checked all other options and they are both in doc and in 
```
Supported options are: +sqlite, +hoplon, +kee-frame, +datomic, +site, +h2, +auth-jwe, +reitit, +reagent, +jetty, +cljs, +graphql, +service, +sassc, +oauth, +swagger, +servlet, +auth, +war, +http-kit, +cucumber, +aleph, +mongodb, +postgres, +boot, +mysql, +re-frame, +kibit, +compojure
```

update available application profiles

---

resources/md/deployment.md

Drop documentation for using Upstart to manage a running Luminus application

---

resources/md/guestbook.md

A proposal for issue #242 
On Windows, java.time.LocalDateTime/now has 0.1-microsecond precision.  This PR updates the documentation to guide readers to create a timestamp column with enough digits for that.
With this change, my guestbook passes tests on Windows (with `lein test`).  I have not tested the change on Macos or Unixes.

Create timestamp with 7 digits of sub-second precision

---

resources/docs-1.x/deployment.md
resources/md/deployment.md
resources/md/guestbook.md
resources/md/profiles.md
resources/md/servers.md
resources/md/websockets.md

Since template version 3.37, Jetty has been the default webserver, but the documentation hasn't matched.  
Though more changes are necessary to update several of the documentation to match this, since `+immutant` is still a viable option, I've removed the references I could find to `immutant` being the default and replaced them with Jetty.

Remove default Immutant References

---

resources/md/deployment.md

instead of _JAVA_OPTIONS, though both seem to work, even on OpenJDK 14.
See https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/envvars002.html.
Also add "Environment=" directive before it, so peeps copy/paste valid unit config.

use the officially supported JAVA_TOOL_OPTIONS env var

---

resources/templates/base.html
resources/templates/contribute.html
resources/templates/docs.html

Set the html header title to unique titles based on the doc title, so we can identify what page we're on.
Currently, we can't distinguish which page of the site we're on when looking at the browser tabs:
After this change:

Add doc title to html header title

---

resources/md/guestbook.md

Tested with a project generated with `lein new luminus guestbook +h2 +immutant`
* Tutorial shows the file should be `test/clj/guestbook/test/db/core.clj` but it is `test/clj/guestbook/db/core_test.clj`
* Tutorial uses the namespace `guestbook.test.db.core` for the tests but it should be `guestbook.db.core-test`

Wrong path and namespace in section "Adding some tests"
