luminus-framework/luminus

- resources/md/guestbook.md
I just did this, lein self-install was deprecated, just lein works as expected.
> self-install is deprecated

- resources/md/routes.md
updates markdown to get "author" from params.
> fixes typo

- resources/md/database.md
> Fix typo in database.md (emial -> email)

- resources/md/learning_clojure.md
> Fixed a typo

- resources/md/html_templating.md
> fix a typo - html_templating

- resources/md/components.md
```clojure
(ns app.db
(:require [mount.core :refer [defstate]]
[app.config :refer [app-config]]))
(defn connect! [] ...)
(defn disconnect! [conn] ...)
(defstate conn :start (connect! app-config)
:stop (disconnect! conn))
```
Here `(defn connect! [] ...)` would take a `config` param.
> [components.md]: adding config param to (connect! [])

- resources/md/deployment.md
The original documentation was mixing upstart and systemd, which made it really difficult to follow for users not familiar with these two systems. Now referring only to systemd, since upstart doesn't work anymore in Ubuntu 15.04.  I also simplified the creation of the `deploy` user.
> Improved Virtual Private Server deployment documentation.

- resources/md/guestbook.md
Corrects the explanation of the cross-site request forgery token
> Fix csrf token explanation

- resources/md/websockets.md
because of https://github.com/luminus-framework/luminus-template/pull/193
> this documentation is no longer needed 

- resources/md/database.md
much thanks for these docs! much appreciated :)
> maintain consistency of fieldnames

- resources/md/security.md
Swapped the position of an article and fixed two typos
> Fix typo in security.md

- resources/md/routes.md
> fix typo in routes.md

- resources/md/apps.md
carwler should have been typed as crawler on app.md
> Fixed a typo on app.md

- resources/md/servers.md
From https://github.com/luminus-framework/luminus-template/issues/254
> Context paths

- resources/public/css/screen.css
- resources/templates/docs.html
This will provide consistent indentation while preserving the disc style "selected" marker
> Use list-style for ul topics selected marker

- resources/md/profiles.md
I was originally confused with how Luminus handles overlapping profiles, so I added this bit to help other beginners.
> Add to profiles.md

- resources/md/components.md
Changes reply to rely in the following context: ... Therefore, in cases where we have functions that
reply on an external resource the management of...
> Minor typo fix.

- resources/md/clojurescript.md
- resources/md/deployment.md
- resources/md/environment.md
- resources/md/html_templating.md
- resources/md/middleware.md
- resources/md/profiles.md
- resources/md/repl.md
- resources/md/responses.md
- resources/md/routes.md
- resources/md/servers.md
- resources/md/services.md
- resources/md/sessions_cookies.md
- resources/md/websockets.md
> Doc fixes and tweaks

- resources/md/datomic.md
Sorry if it isn't that great, wrote this pretty quickly. Happy to clean up any issues and I'll add the other parts as we go.
Bits to add from previous discussion:
> First draft of datomic docs

- resources/md/logging.md
Hi! Thank you for luminus - it's great!
I found a typo on `logging` page and glad to fix it ✌️
> Fix typo in logging.md

- resources/md/deployment.md
Hello!
Think I found a typo.
Thanks again for your work! Luminus keeps growing on me. Helpful to learn the things you woudn't think were possible with Clojure.
Teodor
> Fix inconsistent NREPL port for deployment

- resources/md/deployment.md
see https://serverfault.com/a/695863 and https://serverfault.com/a/890085
> updated systemd config to propely handle the JVM exit status

- resources/md/servers.md
"server" => "serve" - it might not be very noticeable in the diff
> Improve servers.md

- resources/md/profiles.md
To go with this one: https://github.com/luminus-framework/luminus-template/pull/548
> Rename crux -> xtdb

- resources/md/guestbook.md
Fixes luminus-framework/luminus-template#555
> Add disclaimer about dev and test config file

- resources/md/database.md
Adds an example on how to log SQL queries in a new Luminus project.
> Add SQL queries logging instructions to database.md
